-- liquibase formatted sql

-- changeset ilyas:1
CREATE TABLE customer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(50) NOT NULL,
                          last_name VARCHAR(50) NOT NULL,
                          email VARCHAR(100) NOT NULL UNIQUE,
                          phone VARCHAR(20) NOT NULL,
                          code VARCHAR(50) UNIQUE NOT NULL -- ضروري باش تخدم logic ديال uiid-09-xxxx
);

CREATE TABLE menu_item (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(100) NOT NULL,
                           price DECIMAL(10, 2) NOT NULL,
                           available BOOLEAN DEFAULT TRUE
);

CREATE TABLE food_order (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            customer_id BIGINT NOT NULL REFERENCES customer(id),
                            delivery_mode VARCHAR(20) NOT NULL, -- كان سميتو order_type
                            delivery_time TIME NOT NULL,        -- تزاد جديد
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- اختياري
                            total_amount DECIMAL(10, 2)         -- اختياري
);

-- Insert chi menu exemples
INSERT INTO menu_item (name, price) VALUES ('Tajine Poulet', 45.00);
INSERT INTO menu_item (name, price) VALUES ('Pizza Margarita', 35.00);
INSERT INTO menu_item (name, price) VALUES ('Burger Maison', 50.00);